-   id: devtools-document
    name: devtools-document
    description: run devtools::document()
    entry: bin/devtools-document
    language: script
-   id: styler-style-files
    name: styler-style-files
    description: style files with styler
    entry: bin/styler-style-files
    language: script
    files: '(\.R|\.Rmd|\.Rnw|\.r|\.rmd|\.rnw)$'
-   id: check-readme-rmd-rendered
    name: check-readme-rmd-rendered
    description: make sure README.Rmd hasn't been edited more recently than README.md
    entry: bin/check-readme-rmd-rendered
    language: script
    files: '\.[Rr]?md'
