-   id: devtools-document
    name: devtools-document
    description: run devtools::document()
    entry: bin/devtools-document
    language: script
-   id: styler-style-files
    name: styler-style-files
    description: style files with styler
    entry: bin/styler-style-files
    language: script
