# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
# Default configuration for use with tic package
# tic documentation to get started: https://ropenscilabs.github.io/tic/
# Usually you shouldn't need to change the first part of the file

# DO NOT CHANGE THE CODE BELOW
before_install:
  - R -q -e 'if (!requireNamespace("remotes")) install.packages("remotes")'
  - R -q -e 'if (getRversion() < "3.2" && !requireNamespace("curl")) install.packages("curl")'
  - R -q -e 'remotes::install_github("ropenscilabs/tic"); print(tic::dsl_load()); tic::prepare_all_stages()'
  - R -q -e 'tic::before_install()'
install: R -q -e 'tic::install()'
after_install: R -q -e 'tic::after_install()'
before_script: R -q -e 'tic::before_script()'
script: R -q -e 'tic::script()'
after_success: R -q -e 'tic::after_success()'
after_failure: R -q -e 'tic::after_failure()'
before_deploy: R -q -e 'tic::before_deploy()'
deploy:
  provider: script
  script: R -q -e 'tic::deploy()'
  on:
    all_branches: true
after_deploy: R -q -e 'tic::after_deploy()'
after_script: R -q -e 'tic::after_script()'
# DO NOT CHANGE THE CODE ABOVE

# Custom parts:
jobs:
  include:
  - name: r_linux # install pre-commit from R
    stage: after_install
    script:
      - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      - bash miniconda.sh -b -p $HOME/miniconda
      - source "$HOME/miniconda/etc/profile.d/conda.sh"
      - hash -r
      - conda config --set always_yes yes --set changeps1 no
      - conda update -q conda
      - rm miniconda.sh
      - R -q -e 'tic::after_install()'
  - name: r_macOs
    os: osx
    stage: after_install
    script: 
      - R -e -q 'if (!requireNamespace("reticulate")) install.packages("reticulate"); reticulate::install_miniconda()'
      - R -q -e 'tic::after_install()'
  - name: external_linux # install pre-commit outside
    env: 
      - EXTERNAL_INSTALLATION="TRUE"
    stage: after_install
    script:
      - pip install pre-commit --user
      - R -q -e 'tic::after_install()'

language: r
sudo: false
dist: xenial
latex: false

env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=false
  - MAKEFLAGS="-j 2"
