# All available hooks: https://pre-commit.com/hooks.html
# R specific hooks: https://github.com/lorenzwalthert/precommit
repos:
-   repo: https://github.com/lorenzwalthert/precommit
    rev: v0.0.0.9042
    hooks: 
    -   id: parsable-R
    -   id: no-browser-statement
    -   id: lintr
    -   id: readme-rmd-rendered
    -   id: spell-check
        exclude: >
          (?x)^(
          .pre-commit-.*\.yaml|
          .*\.[rR]|
          .*\.py|
          .*\.feather|
          .*\.rds|
          .*\.Rds|
          .*\.RData|
          (.*/|)\.Rprofile|
          (.*/|)\.Renviron|
          (.*/|)\.gitignore|
          (.*/|)\.pre-commit-.*|
          (.*/|)NAMESPACE|
          (.*/|)WORDLIST|
          (.*/|)\.travis.yml|
          (.*/|)appveyor.yml|
          (.*/|)\.Rbuildignore|
          data/.*
          )$
    -   id: style-files
        args: [--style_pkg=styler, --style_fun=tidyverse_style]    
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks: 
    -   id: check-added-large-files
        args: ['--maxkb=200']
    -   id: end-of-file-fixer
        exclude: '\.Rd'
