on:
  schedule:
    - cron:  '20 18 14 * *'

name: Hook dependency updates

jobs:
  hook-dependencies-update:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      RENV_PATHS_ROOT: ~/.local/share/renv
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1
      
      - name: Cache packages
        uses: actions/cache@v1
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            renv-

      - name: renv update
        run: |
          install.packages('renv')
          install.packages('jsonlite')
          renv_deps <- names(jsonlite::read_json('renv.lock')$Packages)
          renv::load()
          can_be_updated <- renv::update(renv_deps)
          renv::snapshot(packages = renv_deps)
        shell: Rscript {0}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3.9.1
        with:
          commit-message: Update renv dependencies
          branch: hook-dependencies-update
          delete-branch: true
          title: 'Hook dependencies update'
          body: |
            This PR updates the hook dependencies in renv.lock, auto-generated 
            by [create-pull-request][1]. Close and re-open this to trigger 
            `on_pull_request` events to circumvent [limitation of GitHub actions](https://github.com/peter-evans/create-pull-request/blob/master/docs/concepts-guidelines.md#push-pull-request-branches-to-a-fork)

            [1]: https://github.com/peter-evans/create-pull-request
